[package]

name = "twilio"
version = "0.1.1"
description = "Rust bindings for the Twilio API"
readme = "README.md"
repository = "https://github.com/neil-lobracco/twilio-rs"
license = "MIT"
authors = ["Neil LoBracco <neil.lobracco@gmail.com>"]
keywords = ["twilio","rust"]

[dependencies]
hyper = "^0.10"
hyper-native-tls = "^0.2"
mime = "^0.2"
rust-crypto = "^0.2"
url="^1.0"
serde = "*"
serde_derive = "*"
serde_json = "*"
base64 = "0.6"